### ISSUE TITLE
Styles.scss should include unstyled-button-styles

### ISSUE THREAD

**Issue by rickyp-uber** [snowcoders/react-popover#6]
If you use popper, the unstyled-button doesn't get styled and it looks like a normal button.

Temporary work around is to import it manually into your code but that's not ideal.

**Comment by k2snowman69** [comment]
This was actually a design decision that we are all sort of regretting now. Here was the scenario:

ComponentA depends on @snowcoders/react-unstyled-button
ComponentB depends on @snowcoders/react-popover which depends on @snowcoders/react-unstyled-button

If we include the styles in @snowcoders/react-unstyled-button's component, they will get added to the dom twice

If we include @snowcoders/react-unstyled-button's css in @snowcoders/react-popover's css then it gets added to the dom twice.

Basically the only way to not have it add to the dom twice was to manage the imports manually in the main.scss of your app.

With that all said, we moved to peer-dependencies recently and someone mentioned after I brought this up that it may not even be an issue anymore because you only ever import a dependency once. So as long as everything is chained via peer-dependencies, you shouldn't get duplicates. We're gonna investigate this and if it's true, we will just import the css with the component which should make everyone's lives easier.

**Comment by k2snowman69** [comment]
Turns out it seems rue so we will stick with peer dependencies (similar to blueprint.js) and go from there!
