### ISSUE TITLE
Need more variability in button

### ISSUE THREAD

**Issue by rickyp-uber** [snowcoders/react-popover#81]
Using this library there is a bit of a frustration regarding how targets fill their space. For inline text and tooltips it works great. But lets say you want to create a dropdown component, the target doesn't fill out the space of the parent making the target be very small. I'll try to write up an example later but figuring I'd open the issue and see if someone already has this issue.

Also, it would be great to be able to use an existing button from a styled library instead of an unstyled button. If I'm aligning to material ui for example, it would be nice to just pass the material ui button instead of having to rewrite the styles for it.

**Comment by k2snowman69** [comment]
Yea we ran into this ourselves.. it's great for tooltips but when you have a button and want to fill out the space it's not super easy.

We were debating on adding a prop like fillSpace to solve this but were unsure of the ramifications considering we would have to know how the parent component is styled. Also in React 16 since the root element may not be rendered by this component, we may not have control over that DOM element.

As far as swapping out the button with a button of your choice: this makes sense. It would have to be a custom target callback and we would likely pass through the type of component to be rendered (we wouldn't want you to give us a button if the type is hover for example). Odds are most people will ignore the argument but providing it is better than not.

We'll look into both and see what we can come up with.

**Comment by k2snowman69** [comment]
Looking into this, in every instance of the Popover, the className passed to `targetClassName` and `popperClassName` are directly applied to the parent element. The parent element is either the containing element or when a wrapper is applied, the wrapperElementType which also has wrapperElementProps so you are able to set the className there.

Now you cannot be sure where the content will be rendered.

All this means you should have all the access you need to set the button content width as much as you would like. For example:
```
<div className="globally-unique-container">
  <Popover
    popperClassName="popperClassName"
    popperContent={<div className="globally-unique-container__popper">Popper</div>}
    targetClassName="targetClassName"
    targetContent={<div className="globally-unique-container__target">Target</div>}
  />
</div>
```
Our current recommendation on writing the css is as follows:
```
.globally-unique-container {
   > .targetClassName {
      height: 100%;
      width: 100%;

      // Descendant selector since you don't know where we will render the content
      .globally-unique-container__target {
         background: green;
       }
   }

   > .popperClassName {
      // Descendant selector since you don't know where we will render the content
      .globally-unique-container__popper {
         background: red;
       }
   }
}
```

And if it were to have a wrapper, to add a child selector  between `.globally-unique-container` and `.targetClassName` and `.popperClassName`. We aren't saying that we wont change this (major versions are major versions for a reason) just that we plan not to nor do we see any reason we will need to in the future. If it does change, it will be breaking.
